/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorPortalRouteImport } from './routes/vendor-portal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SuperAdminTransactionsRouteImport } from './routes/super-admin.transactions'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminOrganizationsRouteImport } from './routes/super-admin.organizations'
import { Route as SuperAdminAccountsRouteImport } from './routes/super-admin.accounts'
import { Route as SolutionsTradeGroupsRouteImport } from './routes/solutions.trade-groups'
import { Route as SolutionsMarketsRouteImport } from './routes/solutions.markets'
import { Route as SolutionsEstatesRouteImport } from './routes/solutions.estates'
import { Route as SolutionsCooperativesRouteImport } from './routes/solutions.cooperatives'
import { Route as ReceiptsReceiptIdRouteImport } from './routes/receipts.$receiptId'
import { Route as DashboardVendorsRouteImport } from './routes/dashboard.vendors'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardReceiptsRouteImport } from './routes/dashboard.receipts'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardDuesRouteImport } from './routes/dashboard.dues'
import { Route as ApiWebhookRouteImport } from './routes/api.webhook'

const VendorPortalRoute = VendorPortalRouteImport.update({
  id: '/vendor-portal',
  path: '/vendor-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SuperAdminTransactionsRoute = SuperAdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOrganizationsRoute = SuperAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAccountsRoute = SuperAdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SolutionsTradeGroupsRoute = SolutionsTradeGroupsRouteImport.update({
  id: '/solutions/trade-groups',
  path: '/solutions/trade-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsMarketsRoute = SolutionsMarketsRouteImport.update({
  id: '/solutions/markets',
  path: '/solutions/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsEstatesRoute = SolutionsEstatesRouteImport.update({
  id: '/solutions/estates',
  path: '/solutions/estates',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsCooperativesRoute = SolutionsCooperativesRouteImport.update({
  id: '/solutions/cooperatives',
  path: '/solutions/cooperatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsReceiptIdRoute = ReceiptsReceiptIdRouteImport.update({
  id: '/receipts/$receiptId',
  path: '/receipts/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVendorsRoute = DashboardVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReceiptsRoute = DashboardReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDuesRoute = DashboardDuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/vendor-portal': typeof VendorPortalRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/dashboard/dues': typeof DashboardDuesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/solutions/cooperatives': typeof SolutionsCooperativesRoute
  '/solutions/estates': typeof SolutionsEstatesRoute
  '/solutions/markets': typeof SolutionsMarketsRoute
  '/solutions/trade-groups': typeof SolutionsTradeGroupsRoute
  '/super-admin/accounts': typeof SuperAdminAccountsRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/transactions': typeof SuperAdminTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/vendor-portal': typeof VendorPortalRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/dashboard/dues': typeof DashboardDuesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/solutions/cooperatives': typeof SolutionsCooperativesRoute
  '/solutions/estates': typeof SolutionsEstatesRoute
  '/solutions/markets': typeof SolutionsMarketsRoute
  '/solutions/trade-groups': typeof SolutionsTradeGroupsRoute
  '/super-admin/accounts': typeof SuperAdminAccountsRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/transactions': typeof SuperAdminTransactionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/terms': typeof TermsRoute
  '/vendor-portal': typeof VendorPortalRoute
  '/api/webhook': typeof ApiWebhookRoute
  '/dashboard/dues': typeof DashboardDuesRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/receipts/$receiptId': typeof ReceiptsReceiptIdRoute
  '/solutions/cooperatives': typeof SolutionsCooperativesRoute
  '/solutions/estates': typeof SolutionsEstatesRoute
  '/solutions/markets': typeof SolutionsMarketsRoute
  '/solutions/trade-groups': typeof SolutionsTradeGroupsRoute
  '/super-admin/accounts': typeof SuperAdminAccountsRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/transactions': typeof SuperAdminTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/super-admin'
    | '/terms'
    | '/vendor-portal'
    | '/api/webhook'
    | '/dashboard/dues'
    | '/dashboard/payments'
    | '/dashboard/receipts'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/vendors'
    | '/receipts/$receiptId'
    | '/solutions/cooperatives'
    | '/solutions/estates'
    | '/solutions/markets'
    | '/solutions/trade-groups'
    | '/super-admin/accounts'
    | '/super-admin/organizations'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/transactions'
    | '/dashboard/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/vendor-portal'
    | '/api/webhook'
    | '/dashboard/dues'
    | '/dashboard/payments'
    | '/dashboard/receipts'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/vendors'
    | '/receipts/$receiptId'
    | '/solutions/cooperatives'
    | '/solutions/estates'
    | '/solutions/markets'
    | '/solutions/trade-groups'
    | '/super-admin/accounts'
    | '/super-admin/organizations'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/transactions'
    | '/dashboard'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/super-admin'
    | '/terms'
    | '/vendor-portal'
    | '/api/webhook'
    | '/dashboard/dues'
    | '/dashboard/payments'
    | '/dashboard/receipts'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/vendors'
    | '/receipts/$receiptId'
    | '/solutions/cooperatives'
    | '/solutions/estates'
    | '/solutions/markets'
    | '/solutions/trade-groups'
    | '/super-admin/accounts'
    | '/super-admin/organizations'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/transactions'
    | '/dashboard/'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  TermsRoute: typeof TermsRoute
  VendorPortalRoute: typeof VendorPortalRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
  ReceiptsReceiptIdRoute: typeof ReceiptsReceiptIdRoute
  SolutionsCooperativesRoute: typeof SolutionsCooperativesRoute
  SolutionsEstatesRoute: typeof SolutionsEstatesRoute
  SolutionsMarketsRoute: typeof SolutionsMarketsRoute
  SolutionsTradeGroupsRoute: typeof SolutionsTradeGroupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendor-portal': {
      id: '/vendor-portal'
      path: '/vendor-portal'
      fullPath: '/vendor-portal'
      preLoaderRoute: typeof VendorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/super-admin/transactions': {
      id: '/super-admin/transactions'
      path: '/transactions'
      fullPath: '/super-admin/transactions'
      preLoaderRoute: typeof SuperAdminTransactionsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/organizations': {
      id: '/super-admin/organizations'
      path: '/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof SuperAdminOrganizationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/accounts': {
      id: '/super-admin/accounts'
      path: '/accounts'
      fullPath: '/super-admin/accounts'
      preLoaderRoute: typeof SuperAdminAccountsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/solutions/trade-groups': {
      id: '/solutions/trade-groups'
      path: '/solutions/trade-groups'
      fullPath: '/solutions/trade-groups'
      preLoaderRoute: typeof SolutionsTradeGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/markets': {
      id: '/solutions/markets'
      path: '/solutions/markets'
      fullPath: '/solutions/markets'
      preLoaderRoute: typeof SolutionsMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/estates': {
      id: '/solutions/estates'
      path: '/solutions/estates'
      fullPath: '/solutions/estates'
      preLoaderRoute: typeof SolutionsEstatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/cooperatives': {
      id: '/solutions/cooperatives'
      path: '/solutions/cooperatives'
      fullPath: '/solutions/cooperatives'
      preLoaderRoute: typeof SolutionsCooperativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$receiptId': {
      id: '/receipts/$receiptId'
      path: '/receipts/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof ReceiptsReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vendors': {
      id: '/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof DashboardVendorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/receipts': {
      id: '/dashboard/receipts'
      path: '/receipts'
      fullPath: '/dashboard/receipts'
      preLoaderRoute: typeof DashboardReceiptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dues': {
      id: '/dashboard/dues'
      path: '/dues'
      fullPath: '/dashboard/dues'
      preLoaderRoute: typeof DashboardDuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardDuesRoute: typeof DashboardDuesRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardReceiptsRoute: typeof DashboardReceiptsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardVendorsRoute: typeof DashboardVendorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDuesRoute: DashboardDuesRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardReceiptsRoute: DashboardReceiptsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardVendorsRoute: DashboardVendorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminAccountsRoute: typeof SuperAdminAccountsRoute
  SuperAdminOrganizationsRoute: typeof SuperAdminOrganizationsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminTransactionsRoute: typeof SuperAdminTransactionsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAccountsRoute: SuperAdminAccountsRoute,
  SuperAdminOrganizationsRoute: SuperAdminOrganizationsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminTransactionsRoute: SuperAdminTransactionsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  TermsRoute: TermsRoute,
  VendorPortalRoute: VendorPortalRoute,
  ApiWebhookRoute: ApiWebhookRoute,
  ReceiptsReceiptIdRoute: ReceiptsReceiptIdRoute,
  SolutionsCooperativesRoute: SolutionsCooperativesRoute,
  SolutionsEstatesRoute: SolutionsEstatesRoute,
  SolutionsMarketsRoute: SolutionsMarketsRoute,
  SolutionsTradeGroupsRoute: SolutionsTradeGroupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
